config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories, only: [:index, :show]
  resources :pois, only: [:index, :show, :new, :create] do
  resources :reviews, only: [:create, :destroy]

  end
 mount Attachinary::Engine => "/attachinary"
  end

  #get 'reviews/create'

  #get 'reviews/new'

  #get 'reviews/show'

  #get 'reviews/edit'

  #get 'reviews/update'

  #get 'pois/index'

  #get 'pois/show'

  #get 'pois/new'

  #get 'pois/create'

  #get 'pois/update'

  #get 'pois/destroy'

  #get 'categories/index'

  #get 'categories/show'

  #get 'categories/new'

  #get 'categories/create'

  #get 'categories/destroy'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pois
end

app/models/poi.rb
class Poi < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many   :reviews, dependent: :destroy
  has_attachment :photo

  validates :category, presence: true
  # validates :user, presence: true
  validates :photo, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  # belongs_to :user
  belongs_to :poi
  validates :comment, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @promoted = Poi.first(3)
  end
end

app/controllers/pois_controller.rb
class PoisController < ApplicationController

  before_action :find_poi, only: [ :show ]

  def index
    @pois = Poi.all

  end

  def show
    @poi = Poi.find(params[:id])
    @review = Review.new
  end

  def new
    @poi = Poi.new
  end

  def create
    @poi = Poi.new(poi_params)
    if @poi.save
      redirect_to poi_path(@poi)
    else
      flash[:alert] = "Erreur lors de la création"
      render :new
    end
  end

  def update
  end

  def destroy
  end

  private

  def find_poi
    @poi = Poi.find(params[:id])
  end

  def poi_params
     params.require(:poi).permit(:title, :caption, :category_id, :longitude, :latitude, :address, :photo)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
  end

  def new
  end

  def show
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Emergence - ATELIERS</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
     <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="conteneurCentral">

<div class="choix">
<!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
   <h1><%= link_to "Espace ARTISTES", new_poi_path %></h1>
   <h1><%= link_to "Espace ARTISANS", new_poi_path %></h1>
  </div>
</div>

  <div class="box size6 color2">
    <div class="banner-home">
      <div class="banner-home-title">
        <h1>Une expérience intense, au coeur de la création</h1>
          <p class="banner-tagline">
          Ce répertoire d'ateliers géolocalisés est un espace de diffusion qui démocratise la découverte des studios d'artistes et d'artisans d'art en proposant une alternative complémentaire à la visite des musées.
          </p>
          <p class="banner-tagline">
          Vous pouvez accéder aux photos et vidéos des ateliers et à toutes les informations concernant les visites libres, les portes ouvertes ou actualités et découvrir leurs productions en avant-première. L'expérience du partage avec l'artiste dans son atelier est un moment privilégié pour explorer l'art sous un angle inédit.</p>
      </div>
    </div>
</div>

  <div class="box size6 color3">
    <h1><%= link_to "Découvrir les ateliers géolocalisés", pois_path, class: "navbar-link" %><%= cl_image_tag("carte_skojbr.png",
      width: 900, height: 500, crop: :fill) %></h1>
  </div>

  <div class="box size3 color3">
    <%= cl_image_tag("zviap0wgrlgvu4jl4fpo.jpg",
      width: 1300, height: 570, crop: :fill) %></div>

<div class="choix">
<!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
   <h1><%= link_to "Recevoir les actualités", new_poi_path %></h1>
  </div>
</div>

  <div class="box size4 color4">
    <%= cl_image_tag("cedric-lamballais-artisan-forgeron-coutelier-s-est_3233015_zjmm9q",
      height: 570, crop: :fill) %>
  </div>

  <div class="box size6 color2"><%= cl_image_tag("soe-studio-about-2_oroszw.jpg",
      height: 570, crop: :fill) %></div>

<div class="box size4 color3"><%= cl_image_tag("1961-KusamastudioNY-full_janvoj.jpg",
       height: 570, crop: :fill) %></div>

  <div class="box size6 color3"><%= cl_image_tag("Screen-shot-2012-07-29-at-9.11.18-PM_n8wgz4",
      height: 570, crop: :fill) %></div>

  <div class="box size2 color2"><%= cl_image_tag("bl1ysuh9amb632r9w5hd.jpg",
      width: 320, height: 560, crop: :fill) %></div>
</div>

app/views/pois/_search.html.erb
<div class="subtitle">
  <div class="container">
    <%= form_tag pois_path, :method => 'get' do %>
      <div class="search">
        <%= text_field_tag :address, '', class: "search-address form-control input-md", placeholder: "Chercher un atelier" %>
        <%= select_tag :category, options_from_collection_for_select(Category.all, "id", "name"), include_blank: "Tout", class: "form-control input-md" %>
        <%= submit_tag "Search", :name => nil, class: "btn btn-default btn-md" %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/pois/create.html.erb
<h1>Pois#create</h1>
<p>Find me in app/views/pois/create.html.erb</p>

app/views/pois/destroy.html.erb
<h1>Pois#destroy</h1>
<p>Find me in app/views/pois/destroy.html.erb</p>

app/views/pois/index.html.erb
<h1>Pois#index</h1>
<p>Find me in app/views/pois/index.html.erb</p>

app/views/pois/new.html.erb
<div class="container">
    <h1>Ajouter un nouvel atelier</h1>

    <%= simple_form_for @poi do |f| %>
      <%= f.input :photo, as: :attachinary %>
      <%= f.input :title %>
      <%= f.input :caption %>

      <div id="submit_new_poi">
        <%= f.button :submit %>
      </div>
    <% end %>
</div>

app/views/pois/show.html.erb
<h1>Pois#show</h1>
<p>Find me in app/views/pois/show.html.erb</p>

app/views/pois/update.html.erb
<h1>Pois#update</h1>
<p>Find me in app/views/pois/update.html.erb</p>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <p>
    ATELIERS : L'art de vivre l'art...
  </p>
  <div class="footer-bottom-content">
    <ul class="social-links">
      <li>
        <a href="">
          <i class="fa fa-facebook" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="">
          <i class="fa fa-twitter" aria-hidden="true"></i>
        </a>
      </li>
      <li>
        <a href="">
          <i class="fa fa-instagram" aria-hidden="true"></i>
        </a>
      </li>
    </ul>
    <small> Politique de confidentialité © 2017 Emergence - ATELIERS, Inc. Tous droits réservés </small>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
 <%= cl_image_tag("logo_ateliers_3_qpjp49.png", :secure=>true, height: 350, crop: :fill) %>

  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "" %>
    <h1>Emergence - ATELIERS : L'art de vivre l'art... <h2>Art of living art...</h2><h4> Arte di vivir el arte... Kunst Lebenkunst... Arto di viva arto...</h4>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>



  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>